### ISSUE TITLE
PyPI Listing

### ISSUE THREAD

**Issue by bsmithyman** [dwfmarchant/pyMKL#2]
Hi Dave,

Should be straightforward to get your package listed on PyPI. When ready, you just need to tag the release (`git tag v?.?.?` or `git tag -s v?.?.?`). This should match the `setup.py` file. Then, you can run

``` shell
python setup.py register -r pypitest
```

to set things up with PyPI testing, and

``` shell
python setup.py register -r pypi
```

to do the same on the live site. After that, `make testpublish` and `make publish` should work.

http://peterdowns.com/posts/first-time-with-pypi.html

**Comment by rowanc1** [comment]
We will be relying on this in the pymatsolver interface lib. See rowanc1/pymatsolver#10 
Mumps works on linux but the mac/pc install is more of a pain.

I would be pretty interested in getting this onto pip so that the install is a bit easier. do you have a timeline or want help?

**Comment by bsmithyman** [comment]
I think this is mostly a question of publishing it...? I believe I did all the setup when we merged the code initially, but I didn't want to scoop @dwfmarchant on the package ownership.

**Comment by dwfmarchant** [comment]
Working on it right now - should be up shortly.

**Comment by rowanc1** [comment]
So awesome. Thank you both!

**Comment by dwfmarchant** [comment]
Ok, I think it's working now.  Maybe worth someone else testing before I close this thing?

**Comment by rowanc1** [comment]
👍 Thanks again for all your help!
