### ISSUE TITLE
Sorted Indices?

### ISSUE THREAD

**Issue by rowanc1** [dwfmarchant/pyMKL#4]
I am having trouble on linux/mac compatibilities. Works on my mac, does not work on travis.

See simpeg/simpeg#401

@jcapriot suggested that there might be an ordering issue. I think this might be good to get into the base repo. I have wrapped it in rowanc1/pymatsolver#13 but probably should be in the base one and ensuring that the final matrix is actually sorted correctly.

``` python
A = A.tocsr()
if not A.has_sorted_indices:
    A.sort_indices()
```

https://software.intel.com/en-us/node/470282

```
CAUTION
Intel MKL PARDISO column indices ja must be in increasing order per row. 
You can validate the sparse matrix structure with the matrix checker (iparm(27))
```

**Comment by dwfmarchant** [comment]
Resolved by 06754fa.
