### ISSUE TITLE
Bug in Nested Disection algorithm in intel's MKL

### ISSUE THREAD

**Issue by jcapriot** [dwfmarchant/pyMKL#6]
Pardiso has a bug in it's nested disection reordering algorithm (both serial and parallel).

Until Intel releases an update to 11.3.4, can you set `iparm[1] = 0` at https://github.com/dwfmarchant/pyMKL/blob/master/pyMKL/pardisoSolver.py#L131

For details on the bug see [https://software.intel.com/en-us/forums/intel-math-kernel-library/topic/657934]

**Comment by rowanc1** [comment]
Can we check the version of MKL and switch it out on the fly?

**Comment by dwfmarchant** [comment]
Sorry, haven't really been paying attention to this project for the last few weeks.  Any idea if this issue is limited to 11.3.3 or is it all versions prior?

**Comment by jcapriot** [comment]
all good, as far as i understand this was only an issue with version 11.3.3. However i'm not sure how long you want to support 11.3.3. Do you know if anaconda has updated their install to 11.3.4 yet?

**Comment by rowanc1** [comment]
I believe this can be closed?

**Comment by dwfmarchant** [comment]
I think so...
